import { execFileSync, spawn, type ChildProcessByStdio } from 'node:child_process';
import { existsSync, mkdirSync, rmSync } from 'node:fs';
import path from 'node:path';
import type { Readable } from 'node:stream';
import {
	request as apiRequest,
	type Browser,
	type BrowserContext,
	type Page
} from '@playwright/test';
import * as OTPAuth from 'otpauth';
import * as m from '../src/lib/paraglide/messages';
import { E2E_LOCALE } from './config';
import { expect, test } from './fixtures';

/**
 * #949, as the owner meets it: someone holds a copy of the owner's session (browser B), and the
 * owner turns two-factor authentication on from their own browser (A). From that moment B must
 * obtain nothing personal from the server, through any of the doors a browser or a script has:
 * a page load, the SvelteKit data endpoint behind it, the full export, and a form action. Then the
 * same for a browser (C) signed in before the owner turns two-factor off. `ASVS v5.0.0-7.4.3`.
 *
 * THE DETECTOR is a pair of values only this run's owner has: the email, and a category name made
 * for the run. Every absence below has its calibration beside it: the same door, asked by the
 * same browser while its session was live, returned the marker. Without that, a door that never
 * carried the marker would pass for one that stopped carrying it.
 *
 * WHY ITS OWN SERVER, like `log-secret-scan.spec.ts`: the suite shares one user, and enrolling it
 * in two-factor would send every later spec to a code page. This one boots the shipped artifact
 * (`node build/index.js`) on its own port and database, and nothing it does reaches the suite's.
 *
 * WHAT IT DOES NOT COVER, measured on the PR and filed separately: the Back button re-showing a
 * page B had already loaded while live (client memory, nothing new from the server), and the
 * interleavings inside one password check, which `pendingSignIn.db-smoke.ts` forces.
 */

test.describe.configure({ mode: 'serial', retries: 0 });

const PORT = 4183;
const BASE_URL = `http://localhost:${PORT}`;
const DB_DIR = path.resolve('e2e/.data/revoked');
const DATABASE_URL = `file:./e2e/.data/revoked/revoked.sqlite`;
const PASSWORD = 'RevokedSessionPassw0rd-41c2!';
const EMAIL = 'revoked-owner-canary@budgetpilot.test';
const CATEGORY = 'RevokedCanaryCategory7f3';
const MARKERS = [EMAIL, CATEGORY];
const STEP_MS = 30_000;

const SERVER_ENV = {
	DATABASE_URL,
	PORT: String(PORT),
	// Without it adapter-node guesses the public URL and the CSRF check refuses every form POST
	// (measured on log-secret-scan.spec.ts).
	ORIGIN: BASE_URL,
	PUBLIC_INSTANCE: 'false',
	REGISTRATION_MODE: 'admin_only',
	PASSWORD_HASH_COST: '12',
	BOOTSTRAP_TOKEN: 'revoked-session-bootstrap-token-5b8e',
	RATE_LIMIT_HASH_SECRET: 'beef'.repeat(16),
	TOTP_ENCRYPTION_KEY: 'face'.repeat(16),
	LLM_ENABLED: 'false',
	BANK_SYNC_ENABLED: 'false'
};

let server: ChildProcessByStdio<null, Readable, Readable> | undefined;
let captured = '';
let secret = '';
let recoveryCodes: string[] = [];
let enrolStep = 0;

/** A code for a given time step, generated by the library, never by the code under test. */
function codeAt(step: number): string {
	return new OTPAuth.TOTP({ secret: OTPAuth.Secret.fromBase32(secret) }).generate({
		timestamp: step * STEP_MS
	});
}

/** How many markers a text carries: the detector, with its count printed beside every use. */
function markerHits(text: string): number {
	return MARKERS.reduce((sum, marker) => sum + text.split(marker).length - 1, 0);
}

async function newBrowser(browser: Browser): Promise<BrowserContext> {
	const context = await browser.newContext({
		baseURL: BASE_URL,
		// This server never issued the suite's stored session.
		storageState: { cookies: [], origins: [] },
		extraHTTPHeaders: { Origin: BASE_URL }
	});
	await context.addCookies([{ name: 'PARAGLIDE_LOCALE', value: E2E_LOCALE, url: BASE_URL }]);
	return context;
}

async function signIn(context: BrowserContext, code?: string): Promise<Page> {
	const page = await context.newPage();
	await page.goto('/login');
	await page.locator('input[name="email"]').fill(EMAIL);
	await page.locator('input[name="password"]').fill(PASSWORD);
	await page.locator('form button[type="submit"]').first().click();
	if (code) {
		await page.waitForURL(/\/login\/verify-totp/);
		await page.locator('input[name="code"]').fill(code);
		await page.locator('form button[type="submit"]').click();
	}
	await page.waitForURL((url) => !url.pathname.startsWith('/login'));
	return page;
}

interface Doors {
	/** A full page load of Settings, in the browser itself. */
	page: { path: string; bytes: number; hits: number };
	/** The data endpoint the client router reads instead of the page. */
	data: { bytes: number; hits: number };
	/** The full export, with the browser's own cookie. */
	export: { status: number; bytes: number; hits: number };
	/** A form action, as a script holding the cookie would post it. */
	action: { type: string };
}

/** Every door, asked by `page`'s browser with whatever cookie it holds now. */
async function knock(page: Page): Promise<Doors> {
	await page.goto('/settings');
	const html = await page.content();
	const request = page.context().request;
	const data = await (await request.get('/settings/__data.json', { maxRedirects: 0 })).text();
	const exported = await request.get('/settings/export', { maxRedirects: 0 });
	const exportedBody = await exported.text();
	const action = await request.post('/settings?/updateAiInsightsEnabled', {
		form: { enabled: 'false' },
		headers: { Accept: 'application/json' },
		maxRedirects: 0
	});
	return {
		page: { path: new URL(page.url()).pathname, bytes: html.length, hits: markerHits(html) },
		data: { bytes: data.length, hits: markerHits(data) },
		export: {
			status: exported.status(),
			bytes: exportedBody.length,
			hits: markerHits(exportedBody)
		},
		action: { type: String(((await action.json()) as { type?: string }).type) }
	};
}

/** Opens the two-factor switch's dialog on Settings and returns it. */
async function openTwoFactorDialog(page: Page) {
	await page.goto('/settings');
	await page.getByRole('switch', { name: m.settings_mfa_switch_aria() }).click();
	const dialog = page.getByRole('dialog');
	await dialog.waitFor();
	return dialog;
}

test.beforeAll(async () => {
	if (!existsSync('build/index.js')) {
		throw new Error('revoked-session: build/index.js is absent, so there is no artifact to boot');
	}
	rmSync(DB_DIR, { recursive: true, force: true });
	mkdirSync(DB_DIR, { recursive: true });
	execFileSync('npx', ['prisma', 'migrate', 'deploy'], {
		env: { ...process.env, DATABASE_URL },
		stdio: 'ignore'
	});
	server = spawn('node', ['build/index.js'], {
		env: { ...process.env, ...SERVER_ENV },
		stdio: ['ignore', 'pipe', 'pipe']
	});
	server.stdout.on('data', (chunk: Buffer) => (captured += chunk.toString()));
	server.stderr.on('data', (chunk: Buffer) => (captured += chunk.toString()));

	const started = Date.now();
	let up = false;
	while (!up && Date.now() - started < 30_000) {
		up = await fetch(`${BASE_URL}/login`).then(
			(response) => response.ok,
			() => false
		);
		if (!up) await new Promise((resolve) => setTimeout(resolve, 100));
	}
	if (!up) throw new Error(`revoked-session: server never became reachable\n${captured}`);

	// The owner and the marker category, through the real actions.
	const client = await apiRequest.newContext({
		baseURL: BASE_URL,
		storageState: { cookies: [], origins: [] },
		extraHTTPHeaders: { Origin: BASE_URL, Accept: 'application/json' }
	});
	const registered = await client.post('/register', {
		form: { email: EMAIL, password: PASSWORD, bootstrapToken: SERVER_ENV.BOOTSTRAP_TOKEN },
		maxRedirects: 0
	});
	expect(((await registered.json()) as { type?: string }).type, 'the owner was registered').toBe(
		'redirect'
	);
	await client.dispose();
});

test.afterAll(() => {
	server?.kill('SIGTERM');
	rmSync(DB_DIR, { recursive: true, force: true });
});

test('turning two-factor on: a browser holding the old session reaches nothing personal', async ({
	browser
}) => {
	const owner = await signIn(await newBrowser(browser));
	const created = await owner.context().request.post('/categories?/createCategory', {
		form: { name: CATEGORY },
		headers: { Accept: 'application/json' }
	});
	expect(((await created.json()) as { type?: string }).type, 'the marker category').toBe('success');
	const thief = await signIn(await newBrowser(browser));

	// Calibration: the same doors, the same browser, while its session is live.
	const live = await knock(thief);
	console.log(`[revoked-session] B live: ${JSON.stringify(live)}`);
	expect.soft(live.page.hits, 'page carries the marker while live').toBeGreaterThan(0);
	expect.soft(live.data.hits, '__data.json carries the marker while live').toBeGreaterThan(0);
	expect.soft(live.export.hits, 'the export carries the marker while live').toBeGreaterThan(0);
	expect.soft(live.action.type, 'the action runs while live').toBe('success');

	// The owner turns two-factor on, in the real dialog.
	const dialog = await openTwoFactorDialog(owner);
	const values = await dialog
		.locator('input')
		.evaluateAll((inputs) =>
			inputs.map((input) => (input as HTMLInputElement).value.replace(/\s+/g, ''))
		);
	secret = values.find((value) => /^[A-Z2-7]{32}$/.test(value)) ?? '';
	expect(secret, 'the key shown for manual entry').toMatch(/^[A-Z2-7]{32}$/);
	enrolStep = Math.floor(Date.now() / STEP_MS);
	await dialog.locator('input[name="currentPassword"]').fill(PASSWORD);
	await dialog.locator('input[name="code"]').fill(codeAt(enrolStep));
	await dialog.locator('button[type="submit"]').click();
	const codes = owner.getByRole('dialog');
	await expect(
		codes.getByRole('heading', { name: m.settings_mfa_recovery_codes_title() })
	).toBeVisible();
	recoveryCodes = (await codes.innerText()).match(/[0-9A-F]{5}-[0-9A-F]{5}/g) ?? [];
	expect(recoveryCodes, 'ten recovery codes').toHaveLength(10);
	await owner.getByRole('button', { name: m.settings_mfa_recovery_codes_confirm() }).click();

	const revoked = await knock(thief);
	console.log(`[revoked-session] B revoked: ${JSON.stringify(revoked)}`);
	expect.soft(revoked.page.path, 'B is sent to sign in').toBe('/login');
	expect.soft(revoked.page.hits, `page: 0 markers in ${revoked.page.bytes} bytes`).toBe(0);
	expect.soft(revoked.data.hits, `__data.json: 0 markers in ${revoked.data.bytes} bytes`).toBe(0);
	expect.soft(revoked.export.hits, `export: 0 markers in ${revoked.export.bytes} bytes`).toBe(0);
	expect.soft(revoked.export.status, 'the export redirects').toBe(303);
	expect.soft(revoked.action.type, 'the action never runs').toBe('redirect');

	// The other half of the ruling: the owner's own browser is still signed in.
	const kept = await knock(owner);
	expect.soft(kept.page.path, 'the owner stays on Settings').toBe('/settings');
	expect.soft(kept.page.hits, 'and still reads their own data').toBeGreaterThan(0);
});

test('turning two-factor off: a browser signed in before it reaches nothing personal', async ({
	browser
}) => {
	expect(secret, 'the first test enrolled two-factor').not.toBe('');
	const owner = await signIn(await newBrowser(browser), recoveryCodes[0]);
	const other = await signIn(await newBrowser(browser), recoveryCodes[1]);

	const live = await knock(other);
	console.log(`[revoked-session] C live: ${JSON.stringify(live)}`);
	expect.soft(live.page.hits, 'page carries the marker while live').toBeGreaterThan(0);
	expect.soft(live.data.hits, '__data.json carries the marker while live').toBeGreaterThan(0);
	expect.soft(live.export.hits, 'the export carries the marker while live').toBeGreaterThan(0);

	// The next step's code: inside the accepted drift, and later than the one enrolment spent.
	const dialog = await openTwoFactorDialog(owner);
	await dialog.locator('input[name="currentPassword"]').fill(PASSWORD);
	await dialog.locator('input[name="code"]').fill(codeAt(enrolStep + 1));
	await dialog.locator('button[type="submit"]').click();
	await expect(owner.getByRole('switch', { name: m.settings_mfa_switch_aria() })).toHaveAttribute(
		'aria-checked',
		'false'
	);

	const revoked = await knock(other);
	console.log(`[revoked-session] C revoked: ${JSON.stringify(revoked)}`);
	expect.soft(revoked.page.path, 'C is sent to sign in').toBe('/login');
	expect.soft(revoked.page.hits, `page: 0 markers in ${revoked.page.bytes} bytes`).toBe(0);
	expect.soft(revoked.data.hits, `__data.json: 0 markers in ${revoked.data.bytes} bytes`).toBe(0);
	expect.soft(revoked.export.hits, `export: 0 markers in ${revoked.export.bytes} bytes`).toBe(0);
	expect.soft(revoked.action.type, 'the action never runs').toBe('redirect');

	const kept = await knock(owner);
	expect.soft(kept.page.path, 'the owner stays on Settings').toBe('/settings');
});
