import { describe, expect, it } from 'vitest';
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

/**
 * No em dashes in prose a reader meets. AGENTS.md carries the rule and the reasoning; this file is
 * the half of it that is enforced.
 *
 * TWO SURFACES, and the boundary is not arbitrary. UI strings and documentation are files, so a
 * test can read them. Commit messages and PR bodies are not, and nothing in this repository can
 * see them, so they stay a convention and AGENTS.md says so rather than implying a check that does
 * not exist.
 *
 * CODE COMMENTS ARE NOT IN SCOPE, and that is the point of the rule's rewrite rather than an
 * omission. The rule used to name them; the tree carried 2 403 em dashes across 348 source files
 * against 18 across 8 prose files when that was measured. A factor of 45 in one direction is a rule
 * that was never about that surface, and gating it would have meant a sweep nobody asked for.
 *
 * Scanned through `git ls-files`, which is what a fresh clone has, so a file that exists only on
 * one machine cannot make this pass or fail. Three groups are excluded and each has a reason that
 * is about authorship, not about convenience.
 */

const REPO_ROOT = fileURLToPath(new URL('../../../', import.meta.url));
const EM_DASH = '—';

/** Not ours to write, or not prose a reader meets. */
const EXCLUDED = [
	// Generated by release-please FROM COMMIT BODIES already on main. It can only ever be as clean
	// as the history behind it, and history is not rewritable to satisfy a lint rule.
	'CHANGELOG.md',
	// Written by `prisma generate`.
	'src/lib/server/database/generated/',
	// Agent definitions. Instructions to a tool, not a page anyone reads.
	'.claude/'
];

/**
 * Deliberate, and each one is a sentence the design draws with a dash. Allowlisted BY KEY rather
 * than by count, so adding a fourth is a decision someone has to write down here rather than a
 * number that quietly goes up.
 */
const ALLOWED_MESSAGE_KEYS = new Set([
	// "Taken by {role} - designate it again": the dash separates a state from its remedy in a row
	// that has room for neither a full stop nor a second line.
	'import_columns_row_vacated',
	// "None - transactions will arrive uncategorised": same shape, same row.
	'import_columns_row_category_empty',
	// The ORIGIN remedy note, where the dash carries the "unless" that follows.
	'origin_mismatch_remedy_note'
]);

function trackedFiles(pattern: string): string[] {
	return execFileSync('git', ['ls-files', pattern], { cwd: REPO_ROOT, encoding: 'utf8' })
		.split('\n')
		.filter(Boolean)
		.filter((path) => !EXCLUDED.some((prefix) => path.startsWith(prefix)));
}

describe('em dashes in prose a reader meets', () => {
	it('scans a non-empty set of files, so a clean result cannot mean an empty list', () => {
		expect.assertions(2);

		// The failure this guards against is the one CLAUDE.md records twice: an absence of output
		// and an absence of failures are the same string and must not be the same verdict. A `git
		// ls-files` that matched nothing would report every assertion below as passing.
		expect(trackedFiles('*.md').length).toBeGreaterThan(30);
		expect(trackedFiles('messages/*.json').length).toBe(2);
	});

	it('finds none in the tracked documentation', () => {
		expect.assertions(1);

		const offenders = trackedFiles('*.md').flatMap((path) =>
			readFileSync(`${REPO_ROOT}${path}`, 'utf8')
				.split('\n')
				.map((line, index) => ({ path, line: index + 1, text: line }))
				.filter((entry) => entry.text.includes(EM_DASH))
				.map((entry) => `${entry.path}:${entry.line}`)
		);

		expect(offenders).toEqual([]);
	});

	it('finds none in either message catalogue, outside the keys allowed by name', () => {
		expect.assertions(1);

		const offenders = trackedFiles('messages/*.json').flatMap((path) => {
			const catalogue = JSON.parse(readFileSync(`${REPO_ROOT}${path}`, 'utf8')) as Record<
				string,
				unknown
			>;
			return Object.entries(catalogue)
				.filter(([, value]) => typeof value === 'string' && value.includes(EM_DASH))
				.filter(([key]) => !ALLOWED_MESSAGE_KEYS.has(key))
				.map(([key]) => `${path}:${key}`);
		});

		expect(offenders).toEqual([]);
	});
});
