import type { RequestEvent } from '@sveltejs/kit';
import { describe, expect, it } from 'vitest';
import { handleLogContext, requestErrorId } from './index';

/**
 * The request context entered before `handleAuth`. The id is generated by the server every time:
 * an inbound `X-Request-Id`, which a trusted proxy forwards exactly as the client sent it, is never
 * read (#250, correction of 2026-10-01).
 */

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;

function eventWith(headers: Record<string, string>, method = 'GET'): RequestEvent {
	return {
		request: new Request('http://localhost/imports/abc', { method, headers }),
		route: { id: '/imports/[batchId]' }
	} as unknown as RequestEvent;
}

async function idSeenBy(event: RequestEvent): Promise<string | undefined> {
	let seen: string | undefined;
	await handleLogContext({
		event,
		resolve: async () => {
			seen = requestErrorId();
			return new Response('ok');
		}
	});
	return seen;
}

describe('handleLogContext', () => {
	it('gives every request a server-generated id, different each time', async () => {
		const first = await idSeenBy(eventWith({}));
		const second = await idSeenBy(eventWith({}));
		expect([UUID.test(first ?? ''), UUID.test(second ?? ''), first === second]).toEqual([
			true,
			true,
			false
		]);
	});

	it('ignores an inbound X-Request-Id, even one that looks like a valid id', async () => {
		const offered = '11111111-1111-4111-8111-111111111111';
		const seen = await idSeenBy(
			eventWith({ 'X-Request-Id': offered, 'X-Correlation-Id': offered })
		);
		expect([UUID.test(seen ?? ''), seen === offered]).toEqual([true, false]);
	});

	it('holds no id outside a request', () => {
		expect(requestErrorId()).toBeUndefined();
	});
});
