import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, it, vi } from 'vitest';
import * as OTPAuth from 'otpauth';
import { isRedirect, type Cookies } from '@sveltejs/kit';
import { env } from '$env/dynamic/private';
import { createSession, hashPassword, readSessionUser, SESSION_COOKIE } from '$lib/server/auth';
import { createMfaChallenge } from '$lib/server/auth/mfaChallenge';
import { encryptTotpSecret, generateTotpSecretBase32 } from '$lib/server/auth/totp';
import { acceptTotpCode } from '$lib/server/auth/totpAcceptance';
import { REAUTH_FIELDS } from '$lib/domain/reauthFields';
import * as m from '$lib/paraglide/messages';
import { prisma } from '$lib/server/db';

/**
 * #818, against a real engine: `ASVS v5.0.0-6.5.1`, « time-based one-time passwords (TOTPs) are only
 * successfully usable once », and RFC 6238 section 5.2, « The verifier MUST NOT accept the second
 * attempt of the OTP after the successful validation has been issued for the first OTP ».
 *
 * THE FIGURE is the issue's: how many times one valid code is ACCEPTED. Measured on main before the
 * change, 2 for two login challenges and 2 for a login followed by a re-authenticated action: the
 * challenge was single use, the code was not. The calibration beside it is a code from a step
 * outside the window, which must be accepted 0 times on both sides, so a 1 below is the code being
 * spent and not a route that refuses everything.
 *
 * Every step is the REAL route action: `/login/verify-totp`'s default action for sign-in, the
 * `/settings` actions for re-authentication, enrolment and disabling. The only thing this file does
 * itself is open the login challenge, which is what `/login`'s action does after the password.
 *
 * THE CLOCK IS PINNED, to the middle of a time step, in `beforeEach`. Every code here is generated
 * for an explicit step relative to that one, so a run that straddles a step boundary cannot turn
 * « refused as reused » into « refused as outside the window ».
 */

if (!process.env.DATABASE_URL) {
	throw new Error(
		'This suite writes to a real database. Set DATABASE_URL (and DATABASE_PROVIDER for a server ' +
			'engine) to a throwaway database explicitly. It refuses to fall back to the default local ' +
			'SQLite file.'
	);
}

if (/(^|[/\\])dev\.db(\?|$)/.test(process.env.DATABASE_URL)) {
	throw new Error(
		'DATABASE_URL points at dev.db, the default local development database. Point it at a ' +
			'throwaway database instead.'
	);
}

const PASSWORD = 'totp-single-use-smoke-password';
const PERIOD_MS = 30_000;
const CONCURRENT = 8;
const CONCURRENT_ACCOUNTS = 4;
const created: string[] = [];

/** The pinned step: every code below is this step plus an offset. */
let step = 0;

/**
 * A documentation address unique to this RUN as well as to the call. The sign-in limiter counts per
 * address, its rows outlive the run, and a reused code is a counted failure: with addresses that
 * repeat from one run to the next, a second run within fifteen minutes on the same database was
 * refused « Too many attempts » where it asserted the reused-code sentence.
 */
const RUN_ID = crypto.randomUUID();
const RUN = `${RUN_ID.slice(0, 4)}:${RUN_ID.slice(4, 8)}`;
let addressCounter = 0;
function freshAddress(): string {
	addressCounter += 1;
	return `2001:db8:${RUN}::${addressCounter.toString(16)}`;
}

/** A code for `step + offset`, generated by the library directly, never by the code under test. */
function codeAt(secret: string, offset: number): string {
	return new OTPAuth.TOTP({ secret: OTPAuth.Secret.fromBase32(secret) }).generate({
		timestamp: (step + offset) * PERIOD_MS
	});
}

async function seedAccount(tag: string, secret?: string) {
	const user = await prisma.user.create({
		data: {
			email: `totp-single-use-${tag}-${crypto.randomUUID()}@budgetpilot.invalid`,
			passwordHash: await hashPassword(PASSWORD),
			...(secret ? { totpEnabled: true, totpSecretEncrypted: encryptTotpSecret(secret) } : {})
		},
		select: { id: true }
	});
	created.push(user.id);
	return user;
}

/** One browser's cookies: what it presents, and what the response writes or deletes. */
function jar(initial: Record<string, string> = {}) {
	const values = new Map(Object.entries(initial));
	const cookies = {
		get: (name: string) => values.get(name),
		set: (name: string, value: string) => {
			values.set(name, value);
		},
		delete: (name: string) => {
			values.delete(name);
		}
	} as unknown as Cookies;
	return { cookies, value: (name: string) => values.get(name) };
}

interface Answer {
	/** Signed in: the action redirected away from the challenge and wrote a session cookie. */
	accepted: boolean;
	/** The sentence a refusal shows, when it is one. */
	error: string | undefined;
}

/**
 * Signs in at the second step: opens a challenge for `userId`, as `/login` does after the password,
 * then posts `code` to the real `/login/verify-totp` action.
 */
async function signInWithCode(userId: string, code: string): Promise<Answer> {
	return submitCode(await openChallenge(userId), code);
}

/** The browser `/login` leaves after the password: a pending challenge cookie and no session. */
async function openChallenge(userId: string) {
	const browser = jar();
	const { passwordHash } = await prisma.user.findUniqueOrThrow({
		where: { id: userId },
		select: { passwordHash: true }
	});
	await createMfaChallenge(userId, passwordHash, browser.cookies);
	return browser;
}

/** Posts `code` to the real `/login/verify-totp` action from a browser holding a challenge. */
async function submitCode(browser: ReturnType<typeof jar>, code: string): Promise<Answer> {
	const { actions } = await import('../../../routes/login/verify-totp/+page.server');
	const run = actions.default as unknown as (event: unknown) => Promise<unknown>;
	const form = new FormData();
	form.set('code', code);
	try {
		const answer = (await run({
			cookies: browser.cookies,
			getClientAddress: () => freshAddress(),
			request: new Request('http://localhost/login/verify-totp', { method: 'POST', body: form }),
			url: new URL('http://localhost/login/verify-totp')
		})) as { data?: { error?: string } };
		return { accepted: false, error: answer.data?.error };
	} catch (thrown) {
		if (!isRedirect(thrown)) throw thrown;
		const signedIn = thrown.location !== '/login' && browser.value(SESSION_COOKIE) !== undefined;
		return { accepted: signedIn, error: undefined };
	}
}

/** A session through the real write path, returned as its token. */
async function mintSession(userId: string): Promise<string> {
	const browser = jar();
	await createSession(userId, browser.cookies);
	return browser.value(SESSION_COOKIE) ?? '';
}

/**
 * Posts `fields` to a real `/settings` action as the browser holding `token`, with `locals.user`
 * resolved by `readSessionUser`, the call `handleAuth` makes.
 */
async function settingsAction(action: string, token: string, fields: Record<string, string>) {
	const { actions } = await import('../../../routes/settings/+page.server');
	const run = actions[action] as unknown as (event: unknown) => Promise<unknown>;
	const form = new FormData();
	for (const [key, value] of Object.entries(fields)) form.set(key, value);
	const browser = jar({ [SESSION_COOKIE]: token });
	return (await run({
		cookies: browser.cookies,
		getClientAddress: () => freshAddress(),
		request: new Request('http://localhost/settings', { method: 'POST', body: form }),
		locals: { user: await readSessionUser(token) },
		url: new URL('http://localhost/settings')
	})) as { status?: number; data?: Record<string, unknown> } & Record<string, unknown>;
}

async function totpEnabled(userId: string): Promise<boolean> {
	const row = await prisma.user.findUniqueOrThrow({
		where: { id: userId },
		select: { totpEnabled: true }
	});
	return row.totpEnabled;
}

beforeAll(() => {
	env.RATE_LIMIT_HASH_SECRET = 'a7'.repeat(32);
	env.TOTP_ENCRYPTION_KEY = 'b8'.repeat(32);
});

beforeEach(() => {
	// Only `Date`: the drivers' own timers keep running. Pinned here and released in `afterEach`, so
	// no test can leave the clock in a state the next one did not choose.
	vi.useFakeTimers({ toFake: ['Date'] });
	step = Math.floor(Date.now() / PERIOD_MS);
	vi.setSystemTime(step * PERIOD_MS + PERIOD_MS / 2);
});

afterEach(() => {
	vi.useRealTimers();
});

afterAll(async () => {
	// Sessions, recovery codes and challenges cascade from User.
	await prisma.user.deleteMany({ where: { id: { in: created } } });
});

describe('one TOTP code is accepted once (v5.0.0-6.5.1, #818)', () => {
	// Separates « the challenge is single use » (2, measured on main) from « the code is » (1).
	it('the same code on two login challenges is accepted once', async () => {
		expect.assertions(1);
		const secret = generateTotpSecretBase32();
		const user = await seedAccount('two-challenges', secret);
		const code = codeAt(secret, 0);

		const answers = [await signInWithCode(user.id, code), await signInWithCode(user.id, code)];
		const accepted = answers.filter((answer) => answer.accepted).length;
		console.log(`[#818] one code, two login challenges: accepted ${accepted} time(s)`);

		expect(accepted).toBe(1);
	});

	// The calibration for the figure above: a code outside the window is refused on every challenge,
	// so the route can refuse, and a 1 above is not a route that accepts every first attempt.
	it('a code outside the window is accepted on no challenge', async () => {
		expect.assertions(1);
		const secret = generateTotpSecretBase32();
		const user = await seedAccount('outside-window', secret);
		const code = codeAt(secret, 2);

		const answers = [await signInWithCode(user.id, code), await signInWithCode(user.id, code)];
		const accepted = answers.filter((answer) => answer.accepted).length;
		console.log(`[#818] calibration, a code two steps ahead: accepted ${accepted} time(s)`);

		expect(accepted).toBe(0);
	});

	// Separates « re-authentication keeps no memory of sign-in » (2, measured on main) from « one
	// record of the last step, consulted by both » (1). `disableTotp` is the action the issue names.
	it('a code used to sign in is accepted once more by no re-authenticated action', async () => {
		expect.assertions(2);
		const secret = generateTotpSecretBase32();
		const user = await seedAccount('login-then-reauth', secret);
		const code = codeAt(secret, 0);

		const signIn = await signInWithCode(user.id, code);
		const token = await mintSession(user.id);
		await settingsAction('disableTotp', token, {
			[REAUTH_FIELDS.password]: PASSWORD,
			[REAUTH_FIELDS.code]: code
		});
		const disabled = !(await totpEnabled(user.id));
		console.log(
			`[#818] one code, sign-in then disableTotp: accepted ${Number(signIn.accepted) + Number(disabled)} time(s)`
		);

		// One assertion per route, so a red names which one accepted.
		expect(signIn.accepted, 'sign-in accepted the code').toBe(true);
		expect(disabled, 'disableTotp accepted the same code').toBe(false);
	});

	// The calibration for the figure above, on the re-authentication side: the same action with a
	// code outside the window changes nothing, and with the NEXT step's code it lands, so the 1 above
	// is the reuse refused and not an action that cannot succeed.
	it('the re-authenticated action refuses an outside code and accepts the next step', async () => {
		expect.assertions(2);
		const secret = generateTotpSecretBase32();
		const user = await seedAccount('reauth-calibration', secret);
		const token = await mintSession(user.id);

		await settingsAction('disableTotp', token, {
			[REAUTH_FIELDS.password]: PASSWORD,
			[REAUTH_FIELDS.code]: codeAt(secret, 2)
		});
		expect(await totpEnabled(user.id)).toBe(true);

		await settingsAction('disableTotp', token, {
			[REAUTH_FIELDS.password]: PASSWORD,
			[REAUTH_FIELDS.code]: codeAt(secret, 1)
		});
		expect(await totpEnabled(user.id)).toBe(false);
	});
});

describe('a reused code is refused for that reason, on both screens', () => {
	it('sign-in says the code was already used', async () => {
		expect.assertions(2);
		const secret = generateTotpSecretBase32();
		const user = await seedAccount('reason-login', secret);
		const code = codeAt(secret, 0);

		expect((await signInWithCode(user.id, code)).accepted).toBe(true);
		expect((await signInWithCode(user.id, code)).error).toBe(m.totp_error_code_reused());
	});

	it('re-authentication says the code was already used', async () => {
		expect.assertions(2);
		const secret = generateTotpSecretBase32();
		const user = await seedAccount('reason-reauth', secret);
		const code = codeAt(secret, 0);

		expect((await signInWithCode(user.id, code)).accepted).toBe(true);
		const token = await mintSession(user.id);
		const answer = await settingsAction('disableTotp', token, {
			[REAUTH_FIELDS.password]: PASSWORD,
			[REAUTH_FIELDS.code]: code
		});
		expect(answer.data?.totpDisableError).toBe(m.totp_error_code_reused());
	});
});

describe('the record of the last step', () => {
	// Separates « read, then write » (several requests read « not used yet », all accepted) from one
	// conditional update the engine serialises (exactly one matches). Run by CI on PostgreSQL and
	// MariaDB; on SQLite locally for this change (#891).
	// The challenges are opened FIRST and the codes then posted together, for several accounts at
	// once: with two submissions that each opened their own challenge, a read-then-write break went
	// red on SQLite and MariaDB and stayed green on PostgreSQL, where one request finished before
	// the other read.
	it('concurrent submissions of one code are accepted exactly once per account', async () => {
		expect.assertions(1);
		const accounts = await Promise.all(
			Array.from({ length: CONCURRENT_ACCOUNTS }, async (_, n) => {
				const secret = generateTotpSecretBase32();
				const user = await seedAccount(`concurrent-${n}`, secret);
				const browsers = [];
				for (let i = 0; i < CONCURRENT; i++) browsers.push(await openChallenge(user.id));
				return { code: codeAt(secret, 0), browsers };
			})
		);

		const accepted = await Promise.all(
			accounts.map(async ({ code, browsers }) => {
				const answers = await Promise.all(browsers.map((browser) => submitCode(browser, code)));
				return answers.filter((answer) => answer.accepted).length;
			})
		);
		console.log(
			`[#818] one code per account, ${CONCURRENT} concurrent challenges each: accepted ${accepted.join(', ')}`
		);

		expect(accepted).toEqual(Array.from({ length: CONCURRENT_ACCOUNTS }, () => 1));
	});

	// Separates « refuse the step just accepted » from « refuse every step at or below it »: the
	// previous step's code is still inside the window, so only the second rule refuses it.
	it('an older code is refused after a newer one, inside the window', async () => {
		expect.assertions(2);
		const secret = generateTotpSecretBase32();
		const user = await seedAccount('older-after-newer', secret);

		expect((await signInWithCode(user.id, codeAt(secret, 1))).accepted).toBe(true);
		expect(await signInWithCode(user.id, codeAt(secret, 0))).toEqual({
			accepted: false,
			error: m.totp_error_code_reused()
		});
	});

	// Separates « enrolment verifies the code » from « enrolment spends it »: the code typed to
	// enable two-factor is a code someone may have watched being typed.
	it("enrolment's confirming code cannot then sign in", async () => {
		expect.assertions(3);
		const user = await seedAccount('enrol');
		const token = await mintSession(user.id);
		const secret = generateTotpSecretBase32();
		const code = codeAt(secret, 0);

		await settingsAction('confirmTotpSetup', token, {
			[REAUTH_FIELDS.password]: PASSWORD,
			[REAUTH_FIELDS.code]: code,
			secretBase32: secret
		});
		expect(await totpEnabled(user.id)).toBe(true);

		expect(await signInWithCode(user.id, code)).toEqual({
			accepted: false,
			error: m.totp_error_code_reused()
		});
		// The calibration: the next step's code signs in, so the refusal is the spent step.
		expect((await signInWithCode(user.id, codeAt(secret, 1))).accepted).toBe(true);
	});

	// Contradiction pass 2 on #818: separates « enrolment records the step of the CODE » from « it
	// records the server's current step ». Every other enrolment here types the current step's code,
	// where the two are the same number; a phone one step ahead is where they differ, and recording
	// the server's step would leave that code usable once more at sign-in.
	it("enrolment records its code's step, not the server's: a code one step ahead cannot then sign in", async () => {
		expect.assertions(2);
		const user = await seedAccount('enrol-ahead');
		const secret = generateTotpSecretBase32();
		const ahead = codeAt(secret, 1);

		await settingsAction('confirmTotpSetup', await mintSession(user.id), {
			[REAUTH_FIELDS.password]: PASSWORD,
			[REAUTH_FIELDS.code]: ahead,
			secretBase32: secret
		});
		expect(await totpEnabled(user.id)).toBe(true);

		expect(await signInWithCode(user.id, ahead)).toEqual({
			accepted: false,
			error: m.totp_error_code_reused()
		});
	});

	// The contradiction pass on #818: a stolen session with no password posts its OWN secret, a code
	// for the next step and a wrong password. Separates « an enrolment code is only verified during
	// re-authentication, and spent by the enabling write » from « spent at verification »: spent
	// there, the account's step moves ahead and the owner's own enrolment, a moment later, is
	// refused as a reused code.
	it("a refused enrolment spends nothing: the owner's enrolment then succeeds", async () => {
		expect.assertions(2);
		const user = await seedAccount('enrol-after-refused');
		const thief = await mintSession(user.id);
		const thiefSecret = generateTotpSecretBase32();

		await settingsAction('confirmTotpSetup', thief, {
			[REAUTH_FIELDS.password]: 'not-the-password',
			[REAUTH_FIELDS.code]: codeAt(thiefSecret, 1),
			secretBase32: thiefSecret
		});
		expect(await totpEnabled(user.id)).toBe(false);

		const owner = await mintSession(user.id);
		const ownerSecret = generateTotpSecretBase32();
		await settingsAction('confirmTotpSetup', owner, {
			[REAUTH_FIELDS.password]: PASSWORD,
			[REAUTH_FIELDS.code]: codeAt(ownerSecret, 0),
			secretBase32: ownerSecret
		});
		expect(await totpEnabled(user.id)).toBe(true);
	});

	// Separates « disabling clears the step with the secret it was a step of » from « it keeps it ».
	// Read from the row, because since enrolment writes its step unconditionally no route behaves
	// differently either way: a re-enrolment test went green with the clearing removed. The column's
	// meaning is what is asserted: NULL, no code accepted since two-factor was last turned off.
	it('disabling clears the last step with the secret', async () => {
		expect.assertions(2);
		const secret = generateTotpSecretBase32();
		const user = await seedAccount('disable-clears', secret);
		const token = await mintSession(user.id);

		await settingsAction('disableTotp', token, {
			[REAUTH_FIELDS.password]: PASSWORD,
			[REAUTH_FIELDS.code]: codeAt(secret, 0)
		});
		expect(await totpEnabled(user.id)).toBe(false);

		const row = await prisma.user.findUniqueOrThrow({
			where: { id: user.id },
			select: { totpLastUsedStep: true }
		});
		expect(row.totpLastUsedStep).toBeNull();
	});
});

/**
 * The contradiction pass 2 on #818: sign-in and re-authentication read the stored ciphertext, then
 * judge and spend the code later (a bcrypt sits in between for re-authentication). These tests call
 * `acceptTotpCode` with the ciphertext read BEFORE the factor changed, which is the call the route
 * makes when the change commits inside that window; no route can be paused there deterministically.
 * Each separates « the update checks the factor the code was judged against » from « it checks the
 * step only », and asserts the verdict and the step as one value so neither goes unobserved.
 */
describe('a code judged against a factor that has since changed is not accepted', () => {
	async function storedCiphertext(userId: string): Promise<string> {
		const row = await prisma.user.findUniqueOrThrow({
			where: { id: userId },
			select: { totpSecretEncrypted: true }
		});
		return row.totpSecretEncrypted ?? '';
	}

	async function lastStep(userId: string): Promise<number | null> {
		const row = await prisma.user.findUniqueOrThrow({
			where: { id: userId },
			select: { totpLastUsedStep: true }
		});
		return row.totpLastUsedStep;
	}

	async function disable(userId: string, secret: string) {
		await settingsAction('disableTotp', await mintSession(userId), {
			[REAUTH_FIELDS.password]: PASSWORD,
			[REAUTH_FIELDS.code]: codeAt(secret, 0)
		});
		expect(await totpEnabled(userId)).toBe(false);
	}

	it('after a disable and a new enrolment, the old secret writes nothing to the new one', async () => {
		expect.assertions(3);
		const oldSecret = generateTotpSecretBase32();
		const user = await seedAccount('stale-after-re-enrol', oldSecret);
		const stale = await storedCiphertext(user.id);
		await disable(user.id, oldSecret);
		const newSecret = generateTotpSecretBase32();
		await settingsAction('confirmTotpSetup', await mintSession(user.id), {
			[REAUTH_FIELDS.password]: PASSWORD,
			[REAUTH_FIELDS.code]: codeAt(newSecret, 0),
			secretBase32: newSecret
		});
		expect(await totpEnabled(user.id)).toBe(true);

		const verdict = await acceptTotpCode(user.id, stale, codeAt(oldSecret, 1));

		expect({ verdict, step: await lastStep(user.id) }).toEqual({ verdict: 'wrong', step });
	});

	it('after a disable, the old secret leaves the disabled row without a step', async () => {
		expect.assertions(2);
		const secret = generateTotpSecretBase32();
		const user = await seedAccount('stale-after-disable', secret);
		const stale = await storedCiphertext(user.id);
		await disable(user.id, secret);

		const verdict = await acceptTotpCode(user.id, stale, codeAt(secret, 1));

		expect({ verdict, step: await lastStep(user.id) }).toEqual({ verdict: 'wrong', step: null });
	});
});
