import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, it, vi } from 'vitest';
import * as OTPAuth from 'otpauth';
import { isRedirect, type Cookies } from '@sveltejs/kit';
import { env } from '$env/dynamic/private';
import { createSession, hashPassword, readSessionUser, SESSION_COOKIE } from '$lib/server/auth';
import { createMfaChallenge } from '$lib/server/auth/mfaChallenge';
import { encryptTotpSecret, generateTotpSecretBase32 } from '$lib/server/auth/totp';
import { REAUTH_FIELDS } from '$lib/domain/reauthFields';
import * as m from '$lib/paraglide/messages';
import { prisma } from '$lib/server/db';

/**
 * #818, against a real engine: `ASVS v5.0.0-6.5.1`, « time-based one-time passwords (TOTPs) are only
 * successfully usable once », and RFC 6238 section 5.2, « The verifier MUST NOT accept the second
 * attempt of the OTP after the successful validation has been issued for the first OTP ».
 *
 * THE FIGURE is the issue's: how many times one valid code is ACCEPTED. Measured on main before the
 * change, 2 for two login challenges and 2 for a login followed by a re-authenticated action: the
 * challenge was single use, the code was not. The calibration beside it is a code from a step
 * outside the window, which must be accepted 0 times on both sides, so a 1 below is the code being
 * spent and not a route that refuses everything.
 *
 * Every step is the REAL route action: `/login/verify-totp`'s default action for sign-in, the
 * `/settings` actions for re-authentication, enrolment and disabling. The only thing this file does
 * itself is open the login challenge, which is what `/login`'s action does after the password.
 *
 * THE CLOCK IS PINNED, to the middle of a time step, in `beforeEach`. Every code here is generated
 * for an explicit step relative to that one, so a run that straddles a step boundary cannot turn
 * « refused as reused » into « refused as outside the window ».
 */

if (!process.env.DATABASE_URL) {
	throw new Error(
		'This suite writes to a real database. Set DATABASE_URL (and DATABASE_PROVIDER for a server ' +
			'engine) to a throwaway database explicitly. It refuses to fall back to the default local ' +
			'SQLite file.'
	);
}

if (/(^|[/\\])dev\.db(\?|$)/.test(process.env.DATABASE_URL)) {
	throw new Error(
		'DATABASE_URL points at dev.db, the default local development database. Point it at a ' +
			'throwaway database instead.'
	);
}

const PASSWORD = 'totp-single-use-smoke-password';
const PERIOD_MS = 30_000;
const CONCURRENT = 8;
const CONCURRENT_ACCOUNTS = 4;
const created: string[] = [];

/** The pinned step: every code below is this step plus an offset. */
let step = 0;

/**
 * A documentation address unique to this RUN as well as to the call. The sign-in limiter counts per
 * address, its rows outlive the run, and a reused code is a counted failure: with addresses that
 * repeat from one run to the next, a second run within fifteen minutes on the same database was
 * refused « Too many attempts » where it asserted the reused-code sentence.
 */
const RUN_ID = crypto.randomUUID();
const RUN = `${RUN_ID.slice(0, 4)}:${RUN_ID.slice(4, 8)}`;
let addressCounter = 0;
function freshAddress(): string {
	addressCounter += 1;
	return `2001:db8:${RUN}::${addressCounter.toString(16)}`;
}

/** A code for `step + offset`, generated by the library directly, never by the code under test. */
function codeAt(secret: string, offset: number): string {
	return new OTPAuth.TOTP({ secret: OTPAuth.Secret.fromBase32(secret) }).generate({
		timestamp: (step + offset) * PERIOD_MS
	});
}

async function seedAccount(tag: string, secret?: string) {
	const user = await prisma.user.create({
		data: {
			email: `totp-single-use-${tag}-${crypto.randomUUID()}@budgetpilot.invalid`,
			passwordHash: await hashPassword(PASSWORD),
			...(secret ? { totpEnabled: true, totpSecretEncrypted: encryptTotpSecret(secret) } : {})
		},
		select: { id: true }
	});
	created.push(user.id);
	return user;
}

/** One browser's cookies: what it presents, and what the response writes or deletes. */
function jar(initial: Record<string, string> = {}) {
	const values = new Map(Object.entries(initial));
	const cookies = {
		get: (name: string) => values.get(name),
		set: (name: string, value: string) => {
			values.set(name, value);
		},
		delete: (name: string) => {
			values.delete(name);
		}
	} as unknown as Cookies;
	return { cookies, value: (name: string) => values.get(name) };
}

interface Answer {
	/** Signed in: the action redirected away from the challenge and wrote a session cookie. */
	accepted: boolean;
	/** The sentence a refusal shows, when it is one. */
	error: string | undefined;
}

/**
 * Signs in at the second step: opens a challenge for `userId`, as `/login` does after the password,
 * then posts `code` to the real `/login/verify-totp` action.
 */
async function signInWithCode(userId: string, code: string): Promise<Answer> {
	return submitCode(await openChallenge(userId), code);
}

/** The browser `/login` leaves after the password: a pending challenge cookie and no session. */
async function openChallenge(userId: string) {
	const browser = jar();
	await createMfaChallenge(userId, browser.cookies);
	return browser;
}

/** Posts `code` to the real `/login/verify-totp` action from a browser holding a challenge. */
async function submitCode(browser: ReturnType<typeof jar>, code: string): Promise<Answer> {
	const { actions } = await import('../../../routes/login/verify-totp/+page.server');
	const run = actions.default as unknown as (event: unknown) => Promise<unknown>;
	const form = new FormData();
	form.set('code', code);
	try {
		const answer = (await run({
			cookies: browser.cookies,
			getClientAddress: () => freshAddress(),
			request: new Request('http://localhost/login/verify-totp', { method: 'POST', body: form }),
			url: new URL('http://localhost/login/verify-totp')
		})) as { data?: { error?: string } };
		return { accepted: false, error: answer.data?.error };
	} catch (thrown) {
		if (!isRedirect(thrown)) throw thrown;
		const signedIn = thrown.location !== '/login' && browser.value(SESSION_COOKIE) !== undefined;
		return { accepted: signedIn, error: undefined };
	}
}

/** A session through the real write path, returned as its token. */
async function mintSession(userId: string): Promise<string> {
	const browser = jar();
	await createSession(userId, browser.cookies);
	return browser.value(SESSION_COOKIE) ?? '';
}

/**
 * Posts `fields` to a real `/settings` action as the browser holding `token`, with `locals.user`
 * resolved by `readSessionUser`, the call `handleAuth` makes.
 */
async function settingsAction(action: string, token: string, fields: Record<string, string>) {
	const { actions } = await import('../../../routes/settings/+page.server');
	const run = actions[action] as unknown as (event: unknown) => Promise<unknown>;
	const form = new FormData();
	for (const [key, value] of Object.entries(fields)) form.set(key, value);
	const browser = jar({ [SESSION_COOKIE]: token });
	return (await run({
		cookies: browser.cookies,
		getClientAddress: () => freshAddress(),
		request: new Request('http://localhost/settings', { method: 'POST', body: form }),
		locals: { user: await readSessionUser(token) },
		url: new URL('http://localhost/settings')
	})) as { status?: number; data?: Record<string, unknown> } & Record<string, unknown>;
}

async function totpEnabled(userId: string): Promise<boolean> {
	const row = await prisma.user.findUniqueOrThrow({
		where: { id: userId },
		select: { totpEnabled: true }
	});
	return row.totpEnabled;
}

beforeAll(() => {
	env.RATE_LIMIT_HASH_SECRET = 'a7'.repeat(32);
	env.TOTP_ENCRYPTION_KEY = 'b8'.repeat(32);
});

beforeEach(() => {
	// Only `Date`: the drivers' own timers keep running. Pinned here and released in `afterEach`, so
	// no test can leave the clock in a state the next one did not choose.
	vi.useFakeTimers({ toFake: ['Date'] });
	step = Math.floor(Date.now() / PERIOD_MS);
	vi.setSystemTime(step * PERIOD_MS + PERIOD_MS / 2);
});

afterEach(() => {
	vi.useRealTimers();
});

afterAll(async () => {
	// Sessions, recovery codes and challenges cascade from User.
	await prisma.user.deleteMany({ where: { id: { in: created } } });
});

describe('one TOTP code is accepted once (v5.0.0-6.5.1, #818)', () => {
	// Separates « the challenge is single use » (2, measured on main) from « the code is » (1).
	it('the same code on two login challenges is accepted once', async () => {
		expect.assertions(1);
		const secret = generateTotpSecretBase32();
		const user = await seedAccount('two-challenges', secret);
		const code = codeAt(secret, 0);

		const answers = [await signInWithCode(user.id, code), await signInWithCode(user.id, code)];
		const accepted = answers.filter((answer) => answer.accepted).length;
		console.log(`[#818] one code, two login challenges: accepted ${accepted} time(s)`);

		expect(accepted).toBe(1);
	});

	// The calibration for the figure above: a code outside the window is refused on every challenge,
	// so the route can refuse, and a 1 above is not a route that accepts every first attempt.
	it('a code outside the window is accepted on no challenge', async () => {
		expect.assertions(1);
		const secret = generateTotpSecretBase32();
		const user = await seedAccount('outside-window', secret);
		const code = codeAt(secret, 2);

		const answers = [await signInWithCode(user.id, code), await signInWithCode(user.id, code)];
		const accepted = answers.filter((answer) => answer.accepted).length;
		console.log(`[#818] calibration, a code two steps ahead: accepted ${accepted} time(s)`);

		expect(accepted).toBe(0);
	});

	// Separates « re-authentication keeps no memory of sign-in » (2, measured on main) from « one
	// record of the last step, consulted by both » (1). `disableTotp` is the action the issue names.
	it('a code used to sign in is accepted once more by no re-authenticated action', async () => {
		expect.assertions(1);
		const secret = generateTotpSecretBase32();
		const user = await seedAccount('login-then-reauth', secret);
		const code = codeAt(secret, 0);

		const signIn = await signInWithCode(user.id, code);
		const token = await mintSession(user.id);
		await settingsAction('disableTotp', token, {
			[REAUTH_FIELDS.password]: PASSWORD,
			[REAUTH_FIELDS.code]: code
		});
		const accepted = Number(signIn.accepted) + Number(!(await totpEnabled(user.id)));
		console.log(`[#818] one code, sign-in then disableTotp: accepted ${accepted} time(s)`);

		expect(accepted).toBe(1);
	});

	// The calibration for the figure above, on the re-authentication side: the same action with a
	// code outside the window changes nothing, and with the NEXT step's code it lands, so the 1 above
	// is the reuse refused and not an action that cannot succeed.
	it('the re-authenticated action refuses an outside code and accepts the next step', async () => {
		expect.assertions(2);
		const secret = generateTotpSecretBase32();
		const user = await seedAccount('reauth-calibration', secret);
		const token = await mintSession(user.id);

		await settingsAction('disableTotp', token, {
			[REAUTH_FIELDS.password]: PASSWORD,
			[REAUTH_FIELDS.code]: codeAt(secret, 2)
		});
		expect(await totpEnabled(user.id)).toBe(true);

		await settingsAction('disableTotp', token, {
			[REAUTH_FIELDS.password]: PASSWORD,
			[REAUTH_FIELDS.code]: codeAt(secret, 1)
		});
		expect(await totpEnabled(user.id)).toBe(false);
	});
});

describe('a reused code is refused for that reason, on both screens', () => {
	it('sign-in says the code was already used', async () => {
		expect.assertions(2);
		const secret = generateTotpSecretBase32();
		const user = await seedAccount('reason-login', secret);
		const code = codeAt(secret, 0);

		expect((await signInWithCode(user.id, code)).accepted).toBe(true);
		expect((await signInWithCode(user.id, code)).error).toBe(m.totp_error_code_reused());
	});

	it('re-authentication says the code was already used', async () => {
		expect.assertions(2);
		const secret = generateTotpSecretBase32();
		const user = await seedAccount('reason-reauth', secret);
		const code = codeAt(secret, 0);

		expect((await signInWithCode(user.id, code)).accepted).toBe(true);
		const token = await mintSession(user.id);
		const answer = await settingsAction('disableTotp', token, {
			[REAUTH_FIELDS.password]: PASSWORD,
			[REAUTH_FIELDS.code]: code
		});
		expect(answer.data?.totpDisableError).toBe(m.totp_error_code_reused());
	});
});

describe('the record of the last step', () => {
	// Separates « read, then write » (several requests read « not used yet », all accepted) from one
	// conditional update the engine serialises (exactly one matches). Run on all three engines by CI.
	// The challenges are opened FIRST and the codes then posted together, for several accounts at
	// once: with two submissions that each opened their own challenge, a read-then-write break went
	// red on SQLite and MariaDB and stayed green on PostgreSQL, where one request finished before
	// the other read.
	it('concurrent submissions of one code are accepted exactly once per account', async () => {
		expect.assertions(1);
		const accounts = await Promise.all(
			Array.from({ length: CONCURRENT_ACCOUNTS }, async (_, n) => {
				const secret = generateTotpSecretBase32();
				const user = await seedAccount(`concurrent-${n}`, secret);
				const browsers = [];
				for (let i = 0; i < CONCURRENT; i++) browsers.push(await openChallenge(user.id));
				return { code: codeAt(secret, 0), browsers };
			})
		);

		const accepted = await Promise.all(
			accounts.map(async ({ code, browsers }) => {
				const answers = await Promise.all(browsers.map((browser) => submitCode(browser, code)));
				return answers.filter((answer) => answer.accepted).length;
			})
		);
		console.log(
			`[#818] one code per account, ${CONCURRENT} concurrent challenges each: accepted ${accepted.join(', ')}`
		);

		expect(accepted).toEqual(Array.from({ length: CONCURRENT_ACCOUNTS }, () => 1));
	});

	// Separates « refuse the step just accepted » from « refuse every step at or below it »: the
	// previous step's code is still inside the window, so only the second rule refuses it.
	it('an older code is refused after a newer one, inside the window', async () => {
		expect.assertions(2);
		const secret = generateTotpSecretBase32();
		const user = await seedAccount('older-after-newer', secret);

		expect((await signInWithCode(user.id, codeAt(secret, 1))).accepted).toBe(true);
		expect(await signInWithCode(user.id, codeAt(secret, 0))).toEqual({
			accepted: false,
			error: m.totp_error_code_reused()
		});
	});

	// Separates « enrolment verifies the code » from « enrolment spends it »: the code typed to
	// enable two-factor is a code someone may have watched being typed.
	it("enrolment's confirming code cannot then sign in", async () => {
		expect.assertions(3);
		const user = await seedAccount('enrol');
		const token = await mintSession(user.id);
		const secret = generateTotpSecretBase32();
		const code = codeAt(secret, 0);

		await settingsAction('confirmTotpSetup', token, {
			[REAUTH_FIELDS.password]: PASSWORD,
			[REAUTH_FIELDS.code]: code,
			secretBase32: secret
		});
		expect(await totpEnabled(user.id)).toBe(true);

		expect(await signInWithCode(user.id, code)).toEqual({
			accepted: false,
			error: m.totp_error_code_reused()
		});
		// The calibration: the next step's code signs in, so the refusal is the spent step.
		expect((await signInWithCode(user.id, codeAt(secret, 1))).accepted).toBe(true);
	});

	// Separates « disabling forgets the old secret's last step » from « it keeps it »: kept, a new
	// secret enrolled within the same step is refused as if its code had been used.
	it('disabling then enrolling a new secret starts from no step', async () => {
		expect.assertions(2);
		const oldSecret = generateTotpSecretBase32();
		const user = await seedAccount('disable-re-enrol', oldSecret);
		const token = await mintSession(user.id);

		await settingsAction('disableTotp', token, {
			[REAUTH_FIELDS.password]: PASSWORD,
			[REAUTH_FIELDS.code]: codeAt(oldSecret, 1)
		});
		expect(await totpEnabled(user.id)).toBe(false);

		// `disableTotp` rotates the session token (#249): the browser now holds a new one.
		const nextToken = await mintSession(user.id);
		const newSecret = generateTotpSecretBase32();
		await settingsAction('confirmTotpSetup', nextToken, {
			[REAUTH_FIELDS.password]: PASSWORD,
			[REAUTH_FIELDS.code]: codeAt(newSecret, 0),
			secretBase32: newSecret
		});
		// Accepted only if disabling cleared the old secret's step, which was ONE AHEAD of this code's.
		// Whether enrolment then records its own step is the test above, not this one.
		expect(await totpEnabled(user.id)).toBe(true);
	});
});
